---
# tasks file for shiva.tomcat
  - name: Installing Installing Tomcat
    package: name={{ item }} state=present
    with_items:
      - tomcat 
      - tomcat-webapps
      - tomcat-admin-webapps

  - name: Copy tomcat users xml file
    template: src=tomcat-users.xml.j2 dest=/etc/tomcat/tomcat-users.xml

  - name: Start Tomcat
    service: name=tomcat state=restarted
